version: "2"

services:
  elasticsearch:
    container_name: Elasticsearch
    image: hyperledgerlinuxone/elasticsearch:latest
    ports: 
     - "9200:9200"
     - "9300:9300"
    restart: always
    volumes:
     - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  
  kibana:
    container_name: Kibana
    image: hyperledgerlinuxone/kibana:latest
    ports:
     - "5601:5601"
    restart: always
    links:
     - elasticsearch
    volumes:
     - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml

  logstash:
    container_name: Logstash
    image: hyperledgerlinuxone/kibana:latest
    ports:
     - "9292:9292"
     - "5043:5043"
     - "5000:5000"
     - "514:514"
    restart: always
    links:
     - elasticsearch
    volumes:
     - ./config/logstash.conf:/etc/logstash/logstash.conf               
